package com.example.ksoapteste2.objetos;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 6/11/2014 3:41:20 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class DispositivoOut implements KvmSerializable {
    
    public int codigoRetorno;
    public boolean codigoRetornoSpecified;
    public String enderecoAcesso;
    public String mensagemRetorno;
    
    public DispositivoOut(){}
    
    public DispositivoOut(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("CodigoRetorno"))
        {
            Object obj = soapObject.getProperty("CodigoRetorno");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                codigoRetorno = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                codigoRetorno = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("CodigoRetornoSpecified"))
        {
            Object obj = soapObject.getProperty("CodigoRetornoSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                codigoRetornoSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                codigoRetornoSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("EnderecoAcesso"))
        {
            Object obj = soapObject.getProperty("EnderecoAcesso");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                enderecoAcesso = j.toString();
            }else if (obj!= null && obj instanceof String){
                enderecoAcesso = (String) obj;
            }
        }
        if (soapObject.hasProperty("MensagemRetorno"))
        {
            Object obj = soapObject.getProperty("MensagemRetorno");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                mensagemRetorno = j.toString();
            }else if (obj!= null && obj instanceof String){
                mensagemRetorno = (String) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return codigoRetorno;
            case 1:
                return codigoRetornoSpecified;
            case 2:
                return enderecoAcesso;
            case 3:
                return mensagemRetorno;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 4;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "CodigoRetorno";
                break;
            case 1:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "CodigoRetornoSpecified";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "EnderecoAcesso";
                break;
            case 3:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "MensagemRetorno";
                break;
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }

	@Override
	public String toString() {
		return "DispositivoOut [codigoRetorno=" + codigoRetorno
				+ ", codigoRetornoSpecified=" + codigoRetornoSpecified
				+ ", enderecoAcesso=" + enderecoAcesso + ", mensagemRetorno="
				+ mensagemRetorno + "]";
	}
    
}
